name: cose_front
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  flutter_riverpod: ^2.5.1  # 상태 관리 라이브러리

  # 라우팅
  go_router: ^14.1.4  # 선언적 라우팅 라이브러리

  # 네트워크 통신
  dio: ^5.4.3+1  # HTTP 클라이언트

  # 데이터 저장
  flutter_secure_storage: ^9.1.1  # 암호화된 키-값 저장소
  sqflite: ^2.3.3+1  # SQLite 데이터베이스
  path_provider: ^2.1.3  # 파일 시스템 경로 제공
  path: ^1.9.0  # 파일 및 디렉토리 경로 조작

  # 모델 및 데이터 처리
  freezed_annotation: ^2.4.4  # 불변 모델 클래스 생성 및 직렬화 지원

  # 유틸리티
  collection: ^1.18.0  # 컬렉션 관련 유틸리티

  # 환경 설정
  flutter_dotenv: ^5.1.0  # .env 파일 사용을 위한 라이브러리

  # UI 컴포넌트
  flutter_svg: ^2.0.10+1  # SVG 렌더링

  # 소셜 로그인
  kakao_flutter_sdk_user: ^1.9.1+2  # 카카오 로그인
  google_sign_in: ^6.2.1  # 구글 로그인
  flutter_naver_login: ^1.8.0  # 네이버 로그인

  # 지도
  flutter_naver_map: ^1.2.3+1  # 네이버 지도
  location: ^7.0.0
  geolocator: ^12.0.0

  # 시스템 기능
  url_launcher: ^6.3.0  # URL 실행
  image_picker: ^1.1.2 # 이미지 설정

  # 토스트 메시지
  flutter_styled_toast: ^2.2.1  # 스타일링 가능한 토스트 메시지

  # 아이콘
  cupertino_icons: ^1.0.6  # iOS 스타일 아이콘

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/marker/
